### ISSUE TITLE
Mod loading error has occurred

### ISSUE THREAD

**Issue by Qian-F** [AceTheEldritchKing/Secrets-Of-Forging-Revelations#3]
https://mclo.gs/R1F4Qur

**Comment by AceTheEldritchKing** [comment]
Are you running the latest version of Tetra? Can you please list all of the mods (and their versions) so I can help you better?

**Comment by AceTheEldritchKing** [comment]
Thank you. I only ask for modlist listed here as I'm on mobile at the moment and the formatting for crash reports becomes harder to read because of it.

If it's only happened once and is unable to be reproduced, I wouldn't worry too much about it. If it happens again, please feel free to make another report here.

**Comment by Qian-F** [comment]
Thank you for your response. If it happens again, I will reply again!
